### ISSUE TITLE
k8s

### ISSUE THREAD

**Issue by xmonader** [waleedhammam/waleeds_vacations#8]
get  started

**Comment by waleedhammam** [comment]
@xmonader any sources please ? :D

**Comment by waleedhammam** [comment]
got started :(, to be done later in other issues

**Comment by xmonader** [comment]
enta msh ht3yat s7?

**Comment by waleedhammam** [comment]
nope :D, to be continued in https://github.com/waleedhammam/waleeds_vacations/issues/9
